services:
  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - chromadb_volume:/chroma/chroma

  chatollama:
    environment:
      - CHROMADB_URL=http://chromadb:8000
      - DATABASE_URL=file:/app/sqlite/chatollama.sqlite
      - REDIS_HOST=redis
      - COHERE_API_KEY=xxxxx
      - COHERE_MODEL=ms-marco-MiniLM-L-6-v2
      - COHERE_BASE_URL=http://peanutshell:8000/v1
    image: 0001coder/chatollama:latest
    pull_policy: always
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ~/.chatollama:/app/sqlite

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data

  peanutshell:
    image: ghcr.io/sugarforever/peanut-shell:latest
    volumes:
      - hf_data:/root/.cache

volumes:
  chromadb_volume:
  redis_data:
  hf_data:
